apiVersion: v1
kind: Template

metadata:
  name: phone-ui

parameters:
  - name: APPLICATION_NAME
    value: phone-ui
    required: true
  - name: ROUTE_NAME
    value: game
    required: true
  - name: PUBLIC_URL
    value: redhatkeynote.com
  - name: PUBLIC_NAME
    value: game-keynote

objects:
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${ROUTE_NAME}
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}

  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME} 
      name: ${PUBLIC_NAME}
    spec:
      host: ${PUBLIC_URL} 
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}
