apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 2.4.0
  replicas: 1
  connectCluster: "hq"
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  clusters:
  - alias: "hq"
    bootstrapServers: my-cluster-kafka-bootstrap:9092
  mirrors: {}