#!/usr/bin/env bash

createTopics::run() {
  header_text "\n\n######## leaderboard::deploy:: Create Leaderboard Topics ########\n"
  oc create -n "$(kafkanamespace)" -f "$(configdir)/topics.yaml" || true
}

createTopics::usage(){
  echo "No parameters"
}

createTopics::clean(){
  header_text "\n\n######## leaderboard::deploy:: Delete Leaderboard Topics ########\n"
  oc delete -n "$(kafkanamespace)" -f "$(configdir)/topics.yaml" || true
}

createTopics::description(){
  echo "Creates Leaderboard Topics"
}