#!/usr/bin/env bash

createProjects::run() {
 oc new-project "$(project)" --description-"Leaderboard demo applications"
}

createProjects::usage(){
  echo "No parameters"
}

createProjects::clean(){
  echo "Not implemented"
}

createProjects::description(){
  echo "Installs PostgreSQL Persistent Template"
}