#!/usr/bin/env bash

deployLeaderboardAPI::run() { 
 header_text "\n\n######## leaderboard::deploy:: Deploying Leaderboard API ########\n"
 oc import-image 2020-leaderboard-api \
   --from=quay.io/redhatdemo/2020-leaderboard-api \
   --confirm
}

deployLeaderboardAPI::usage(){
  echo "No parameters"
}

deployLeaderboardAPI::clean(){
  echo "WIP"
}

deployLeaderboardAPI::description(){
  echo "Deploy Leaderboard Applications"
}