#!/usr/bin/env bash

deployLeaderboardMessaging::run() { 
  header_text "\n\n######## leaderboard::deploy:: Deploying Leaderboard Messaging ########\n"
  oc import-image 2020-leaderboard-messaging \
    --from=quay.io/redhatdemo/2020-leaderboard-messaging \
    --confirm
}

deployLeaderboardMessaging::usage(){
  echo "No parameters"
}

deployLeaderboardMessaging::clean(){
  echo "WIP"
}

deployLeaderboardMessaging::description(){
  echo "Deploy Leaderboard Messaging application"
}