#!/usr/bin/env bash

deployLeaderboardBroadcast::run() { 
  header_text "\n\n######## leaderboard::deploy:: Deploying Leaderboard Broadcast ########\n"
  oc import-image 2020-leaderboard-broadcast \
    --from=quay.io/redhatdemo/2020-leaderboard-broadcast \
    --confirm
}

deployLeaderboardBroadcast::usage(){
  echo "No parameters"
}

deployLeaderboardBroadcast::clean(){
  echo "WIP"
}

deployLeaderboardBroadcast::description(){
  echo "Deploy Leaderboard Brodcast application"
}