#!/usr/bin/env bash

deployLeaderboard::run() {
  header_text "\n\n######## leaderboard::deploy:: Deploying Leaderboard Aggregator ########\n"
  oc import-image 2020-leaderboard-aggregator \
    --from=quay.io/redhatdemo/2020-leaderboard-aggregator \
    --confirm
}

deployLeaderboard::usage(){
  echo "No parameters"
}

deployLeaderboard::clean(){
  echo "WIP"
}

deployLeaderboard::description(){
  echo "Deploy Leaderboard Applications"
}