#!/usr/bin/env bash

installLeaderboardAPI::run() {
  header_text "\n\n######## leaderboard::deploy:: Install Leaderboard API ########\n"  
  cat "$(configdir)/leaderboard-api.yaml" | envsubst \
    | oc apply -n "$(project)" --dry-run=${DRY_RUN:-false} -f -
}

installLeaderboardAPI::usage(){
  echo "No parameters"
}

installLeaderboardAPI::clean(){
 header_text "\n\n######## leaderboard::deploy:: Delete Leaderboard API ########\n"  
  LEADER_PARAMS="IMAGE_REPOSITORY=2020-leaderboard-aggregator \
   -p REPLICAS=$LEADERBOARD_API_REPLICAS"
  oc delete -f "$(configdir)/leaderboard-api.yaml"
}

installLeaderboardAPI::description(){
  echo "Install Leaderboard API"
}