#!/usr/bin/env bash

installPostgresql::run() {
 header_text "Deploying PostgeSQL"
 oc import-image openshift-pgsql12-primary \
   --from=quay.io/redhatdemo/openshift-pgsql12-primary \
   --confirm
 POSTGRESQL_PARAMS="PG_NETWORK_MASK=all"  
 oc process -f "$(configdir)/openshift-pgsql12-template.json" $POSTGRESQL_PARAMS | oc apply -n"$(project)" -f -
 
 sleep 5; while echo && oc get pods -n "$(project)" --selector=deploymentconfig=postgresql \
   | grep -v -E "(Running|Completed|STATUS)"; do sleep 5; done

 oc create configmap -n"$(project)" leaderboard-schema \
   --from-file=schema.sql="$(configdir)/schema.sql"
   
 oc create -n"$(project)" -f "$(configdir)/leaderboard-schema-job.yaml"
}

installPostgresql::usage(){
  echo "No parameters"
}

installPostgresql::clean(){
  header_text "UnDeploying PostgeSQL"
 POSTGRESQL_PARAMS="PG_NETWORK_MASK=all"
 oc process -f "$(configdir)/openshift-pgsql12-template.json"  $POSTGRESQL_PARAMS | oc delete -n"$(project)" -f -
 oc delete configmap -n"$(project)" leaderboard-schema
 oc delete -n"$(project)" -f "$(configdir)/leaderboard-schema-job.yaml"
}

installPostgresql::description(){
  echo "Installs PostgreSQL Persistent Template"
}