#!/usr/bin/env bash

installLeaderboard::run() {
  local appName="lbagg-"
  IFS=',' read -ra edgeTopics <<< "$KAFKA_STREAMS_TOPICS"
  for topic in "${edgeTopics[@]}"
  do
    header_text "\n\n######## leaderboard::deploy:: Install Leaderboard Aggregator:: $appName${topic/./-}  ########\n"
    LEADER_PARAMS="REPLICAS=$LEADERBOARD_AGGREGATOR_REPLICAS \
      -p APPLICATION_NAME=$appName${topic/./-} \
      -p KAFKA_STREAMS_TOPIC=$topic"
    oc process -f "$(configdir)/leaderboard-aggregator.yaml" $LEADER_PARAMS | oc apply -n "$(project)" -f -
  done
}

installLeaderboard::usage(){
  echo "No parameters"
}

installLeaderboard::clean(){
  local appName="lbagg-"
  IFS=',' read -ra edgeTopics <<< "$KAFKA_STREAMS_TOPICS"
  for topic in "${edgeTopics[@]}"
  do
    header_text "\n\n######## leaderboard::deploy:: Delete Leaderboard Aggregator:: $appName${topic/./-}  ########\n"
    LEADER_PARAMS="REPLICAS=$LEADERBOARD_AGGREGATOR_REPLICAS \
      -p APPLICATION_NAME=$appName${topic/./-} \
      -p KAFKA_STREAMS_TOPIC=$topic \
      -p PG_SECRET=openshift-pgsql12-primary-secret"
    oc process -f "$(configdir)/leaderboard-aggregator.yaml" $LEADER_PARAMS | oc delete -n "$(project)" -f -
  done
}

installLeaderboard::description(){
  echo "Install Leaderboard Applications"
}