#!/usr/bin/env bash

installNexus::run() {
  header_text "\n\n######## leaderboard::deploy:: Install Nexus Maven Repo ########\n"  
  oc new-app -n"$(project)" sonatype/nexus
  sleep 5; 
  while (echo && oc get pods -n "$(project)" \
    --selector=deploymentconfig=nexus \
    | grep -v -E "(Running|Completed|STATUS)";) 
  do 
     header_text "\n Waiting for nexus to be ready ... \n"
     sleep 5; 
  done
}

installNexus::usage(){
  echo "No parameters"
}

installNexus::clean(){
  echo "WIP"
}

installNexus::description(){
  echo "Install Nexus Maven Repository"
}