#!/usr/bin/env bash

installLeaderboardMessaging::run() {
  header_text "\n\n######## leaderboard::deploy:: Install Leaderboard Messaging ########\n"  
  cat "$(configdir)/leaderboard-messaging.yaml" | envsubst \
    | oc apply -n "$(project)" --dry-run=${DRY_RUN:-false} -f -
}

installLeaderboardMessaging::usage(){
  echo "No parameters"
}

installLeaderboardMessaging::clean(){
  header_text "\n\n######## leaderboard::deploy:: Delete Leaderboard Messaging ########\n"  
  oc delete -f "$(configdir)/leaderboard-messaging.yaml" 
}

installLeaderboardMessaging::description(){
  echo "Install Leaderboard Messaging"
}