#!/usr/bin/env bash

installLeaderboardBroadcast::run() {
  header_text "\n\n######## leaderboard::deploy:: Install Leaderboard Broadcast ########\n"  
  cat "$(configdir)/leaderboard-broadcast.yaml"| envsubst \
    | oc apply -n "$(project)" --dry-run=${DRY_RUN:-false} -f -
}

installLeaderboardBroadcast::usage(){
  echo "No parameters"
}

installLeaderboardBroadcast::clean(){
  header_text "\n\n######## leaderboard::deploy:: Delete Leaderboard Broadcast ########\n"  
  oc delete -f "$(configdir)/leaderboard-broadcast.yaml"
}

installLeaderboardBroadcast::description(){
  echo "Install Leaderboard Broadcast"
}