#!/usr/bin/env bash

installLeaderboardMessaging::run() {
  header_text "\n\n######## leaderboard::deploy:: Install Leaderboard Messaging ########\n"  
  LEADER_PARAMS="IMAGE_REPOSITORY=2020-leaderboard-messaging \
   -p REPLICAS=$LEADERBOARD_MESSAGING_REPLICAS"
  oc process -f "$(configdir)/leaderboard-messaging.yaml" $LEADER_PARAMS | oc apply -n "$(project)" -f -
}

installLeaderboardMessaging::usage(){
  echo "No parameters"
}

installLeaderboardMessaging::clean(){
  echo "WIP"
}

installLeaderboardMessaging::description(){
  echo "Install Leaderboard Messaging"
}