apiVersion: v1
kind: Template
labels:
  template: datagrid-service
metadata:
  labels:
    template: datagrid-service
  name: datagrid-service
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: datagrid-service
      name: datagrid-ping
    spec:
      clusterIP: None
      ports:
      - name: ping
        port: 7800
        protocol: TCP
        targetPort: 7800
      selector:
        deploymentConfig: datagrid-service
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        application: datagrid-service
      name: datagrid-service
    spec:
      ports:
      - name: single-port
        port: 11222
        targetPort: 11222
      selector:
        deploymentConfig: datagrid-service
  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      labels:
        application: datagrid-service
      name: datagrid-service
    spec:
      replicas: 2
      serviceName: datagrid-ping
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 20
          intervalSeconds: 20
          timeoutSeconds: 1200
          maxUnavailable: 1
          maxSurge: 1
      template:
        metadata:
          labels:
            application: datagrid-service
            deploymentConfig: datagrid-service
          name: datagrid-service
        spec:
          containers:
          - env:
            - name: CONFIG_PATH
              value: /config/server.yaml
            - name: MANAGED_ENV
              value: "TRUE"
            image: quay.io/infinispan/server@sha256:3ca725718bfd046c4f12252d7ed6ec67622e2ab3fe15777f1297e3ee59363373
            name: datagrid-service
            ports:
            - containerPort: 7800
              name: ping
              protocol: TCP
            - containerPort: 11222
              name: hotrod
              protocol: TCP
            livenessProbe:
              httpGet:
                path: /rest/v2/cache-managers/default/health/status
                port: 11222
              failureThreshold: 5
              initialDelaySeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              httpGet:
                path: /rest/v2/cache-managers/default/health/status
                port: 11222
              failureThreshold: 5
              initialDelaySeconds: 10
              successThreshold: 1
              timeoutSeconds: 10
            resources:
              limits:
                memory: 2048Mi
              requests:
                cpu: "1"
                memory: 2048Mi
            volumeMounts:
            - mountPath: /config
              name: config-volume
          volumes:
            - name: config-volume
              configMap:
                name: datagrid-configuration
